version: '3.5'

networks:
  laravel-example-app:

services:

  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./infra/docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./infra/docker/logs/nginx:/var/log/nginx
    restart: unless-stopped
    depends_on:
      - app
    networks:
      - laravel-example-app

  mysql:
    image: mysql:latest
    container_name: mysql
    command: ['--default-authentication-plugin=mysql_native_password']
    restart: unless-stopped
    tty: true
    ports:
      - '33088:3306'
    volumes:
      - database-volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: database
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - laravel-example-app

  app:
    build:
      context: infra/docker/php-fpm
    container_name: app
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./infra/docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini
    ports:
      - '9000:9000'
    networks:
      - laravel-example-app

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - '8585:80'
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    networks:
      - laravel-example-app

volumes:
  database-volume:
    driver: "local"
